const ACTIONS = {
  SET_DATA_LOADING: "SET_DATA_LOADING",
  SET_GEO_LOCATION: "SET_GEO_LOCATION",
  SET_COUNTRY_INFORMATION: "SET_COUNTRY_INFORMATION",
  SET_COVID19_STATS: "SET_COVID19_STATS",
  SET_PHOTOS: "SET_PHOTOS",
  SET_NEWS: "SET_NEWS",
  SET_TWEETS: "SET_TWEETS",
};

export default ACTIONS;
